/*
 * SendVerify API
 * Improve deliverability of your email list by automatically cleaning all emails before sending to them. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsAccount', 'model/ModelsEAccount'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsAccount'), require('../model/ModelsEAccount'));
  } else {
    // Browser globals (root is window)
    if (!root.SendVerifyApi) {
      root.SendVerifyApi = {};
    }
    root.SendVerifyApi.XauthApi = factory(root.SendVerifyApi.ApiClient, root.SendVerifyApi.ModelsAccount, root.SendVerifyApi.ModelsEAccount);
  }
}(this, function(ApiClient, ModelsAccount, ModelsEAccount) {
  'use strict';

  /**
   * Xauth service.
   * @module api/XauthApi
   * @version 1.0.0
   */

  /**
   * Constructs a new XauthApi. 
   * @alias module:api/XauthApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the xAuthRouterCreateAccountViaAPI operation.
     * @callback module:api/XauthApi~xAuthRouterCreateAccountViaAPICallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsAccount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Account, sub-account and member <br>
     * @param {module:model/ModelsEAccount} body The Account content
     * @param {String} xMasterAccountApiKey Master Account Api Key
     * @param {module:api/XauthApi~xAuthRouterCreateAccountViaAPICallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsAccount}
     */
    this.xAuthRouterCreateAccountViaAPI = function(body, xMasterAccountApiKey, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling xAuthRouterCreateAccountViaAPI");
      }

      // verify the required parameter 'xMasterAccountApiKey' is set
      if (xMasterAccountApiKey === undefined || xMasterAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xMasterAccountApiKey' when calling xAuthRouterCreateAccountViaAPI");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Master-Account-ApiKey': xMasterAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsAccount;

      return this.apiClient.callApi(
        '/xauth/create', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
