/*
 * SendVerify API
 * Improve deliverability of your email list by automatically cleaning all emails before sending to them. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendVerifyApi);
  }
}(this, function(expect, SendVerifyApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsEAccountMember', function() {
      beforeEach(function() {
        instance = new SendVerifyApi.ModelsEAccountMember();
      });

      it('should create an instance of ModelsEAccountMember', function() {
        // TODO: update the code to test ModelsEAccountMember
        expect(instance).to.be.a(SendVerifyApi.ModelsEAccountMember);
      });

      it('should have the property uid (base name: "uid")', function() {
        // TODO: update the code to test the property uid
        expect(instance).to.have.property('uid');
        // expect(instance.uid).to.be(expectedValueLiteral);
      });

      it('should have the property verifyEmail (base name: "verifyEmail")', function() {
        // TODO: update the code to test the property verifyEmail
        expect(instance).to.have.property('verifyEmail');
        // expect(instance.verifyEmail).to.be(expectedValueLiteral);
      });

    });
  });

}));
