/*
 * SendVerify API
 * Improve deliverability of your email list by automatically cleaning all emails before sending to them. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendVerifyApi);
  }
}(this, function(expect, SendVerifyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendVerifyApi.ClusterApi();
  });

  describe('(package)', function() {
    describe('ClusterApi', function() {
      describe('clusterRouterDeleteItemFromCacheOfEveryNodeInCluster', function() {
        it('should call clusterRouterDeleteItemFromCacheOfEveryNodeInCluster successfully', function(done) {
          // TODO: uncomment, update parameter values for clusterRouterDeleteItemFromCacheOfEveryNodeInCluster call
          /*
          var xSystemApiKey = "xSystemApiKey_example";
          var opts = {};
          opts.name = "name_example";
          opts.key = "key_example";

          instance.clusterRouterDeleteItemFromCacheOfEveryNodeInCluster(xSystemApiKey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('clusterRouterGetItemFromCacheOfSpecificNodeInCluster', function() {
        it('should call clusterRouterGetItemFromCacheOfSpecificNodeInCluster successfully', function(done) {
          // TODO: uncomment, update parameter values for clusterRouterGetItemFromCacheOfSpecificNodeInCluster call
          /*
          var xSystemApiKey = "xSystemApiKey_example";
          var opts = {};
          opts.name = "name_example";
          opts.key = "key_example";

          instance.clusterRouterGetItemFromCacheOfSpecificNodeInCluster(xSystemApiKey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
